//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWS.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento mensaje del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ClientWS.ServiceReference1.HelloWorldResponse HelloWorld(ClientWS.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWS.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ClientWS.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento mensaje del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomXML", ReplyAction="*")]
        ClientWS.ServiceReference1.CustomXMLResponse CustomXML(ClientWS.ServiceReference1.CustomXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomXML", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWS.ServiceReference1.CustomXMLResponse> CustomXMLAsync(ClientWS.ServiceReference1.CustomXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ClientWS.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ClientWS.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mensaje;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(string mensaje) {
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWS.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ClientWS.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomXML", Namespace="http://tempuri.org/", Order=0)]
        public ClientWS.ServiceReference1.CustomXMLRequestBody Body;
        
        public CustomXMLRequest() {
        }
        
        public CustomXMLRequest(ClientWS.ServiceReference1.CustomXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mensaje;
        
        public CustomXMLRequestBody() {
        }
        
        public CustomXMLRequestBody(string mensaje) {
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientWS.ServiceReference1.CustomXMLResponseBody Body;
        
        public CustomXMLResponse() {
        }
        
        public CustomXMLResponse(ClientWS.ServiceReference1.CustomXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustomXMLResult;
        
        public CustomXMLResponseBody() {
        }
        
        public CustomXMLResponseBody(string CustomXMLResult) {
            this.CustomXMLResult = CustomXMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ClientWS.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ClientWS.ServiceReference1.WebService1Soap>, ClientWS.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWS.ServiceReference1.HelloWorldResponse ClientWS.ServiceReference1.WebService1Soap.HelloWorld(ClientWS.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string mensaje) {
            ClientWS.ServiceReference1.HelloWorldRequest inValue = new ClientWS.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ClientWS.ServiceReference1.HelloWorldRequestBody();
            inValue.Body.mensaje = mensaje;
            ClientWS.ServiceReference1.HelloWorldResponse retVal = ((ClientWS.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWS.ServiceReference1.HelloWorldResponse> ClientWS.ServiceReference1.WebService1Soap.HelloWorldAsync(ClientWS.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWS.ServiceReference1.HelloWorldResponse> HelloWorldAsync(string mensaje) {
            ClientWS.ServiceReference1.HelloWorldRequest inValue = new ClientWS.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ClientWS.ServiceReference1.HelloWorldRequestBody();
            inValue.Body.mensaje = mensaje;
            return ((ClientWS.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWS.ServiceReference1.CustomXMLResponse ClientWS.ServiceReference1.WebService1Soap.CustomXML(ClientWS.ServiceReference1.CustomXMLRequest request) {
            return base.Channel.CustomXML(request);
        }
        
        public string CustomXML(string mensaje) {
            ClientWS.ServiceReference1.CustomXMLRequest inValue = new ClientWS.ServiceReference1.CustomXMLRequest();
            inValue.Body = new ClientWS.ServiceReference1.CustomXMLRequestBody();
            inValue.Body.mensaje = mensaje;
            ClientWS.ServiceReference1.CustomXMLResponse retVal = ((ClientWS.ServiceReference1.WebService1Soap)(this)).CustomXML(inValue);
            return retVal.Body.CustomXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWS.ServiceReference1.CustomXMLResponse> ClientWS.ServiceReference1.WebService1Soap.CustomXMLAsync(ClientWS.ServiceReference1.CustomXMLRequest request) {
            return base.Channel.CustomXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWS.ServiceReference1.CustomXMLResponse> CustomXMLAsync(string mensaje) {
            ClientWS.ServiceReference1.CustomXMLRequest inValue = new ClientWS.ServiceReference1.CustomXMLRequest();
            inValue.Body = new ClientWS.ServiceReference1.CustomXMLRequestBody();
            inValue.Body.mensaje = mensaje;
            return ((ClientWS.ServiceReference1.WebService1Soap)(this)).CustomXMLAsync(inValue);
        }
    }
}
